; PlatformIO Project Configuration File
;
; Modul 05 - SysTick: blinky LED via interrupt SysTick.
; Board : ST STM32F4DISCOVERY (disco_f407vg)

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube
