; PlatformIO Project Configuration File
;
; Modul 02 - Direct IO: LED bawaan (LD4 / PD12) berkedip.
; Board : ST STM32F4DISCOVERY (disco_f407vg)

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube
