; PlatformIO Project Configuration File
;
; Modul 02 - Direct IO: tombol USER (PA0) mengendalikan LED LD4 (PD12).
; Board : ST STM32F4DISCOVERY (disco_f407vg)

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube
